fix: make sure pip install from github works (#178)
pip install from github was failing with the following error:

```
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/8l/klypdyl51dvb7_1kztfgsv8m0000gn/T/pip-req-build-vx02zbxx/setup.py", line 20, in <module>
          from ansibleplaybookgrapher import __version__, __prog__
        File "/private/var/folders/8l/klypdyl51dvb7_1kztfgsv8m0000gn/T/pip-req-build-vx02zbxx/ansibleplaybookgrapher/__init__.py", line 18, in <module>
          from ansible.utils.display import Display
      ModuleNotFoundError: No module named 'ansible'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

This is due to setup tools trying to inspect the files during the
installation process while some of dependencies are not installed yet.

---------

Co-authored-by: haidaraM <haidaraM@users.noreply.github.com>